// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/Bo0mer/enslaver/enslaver"
	. "github.com/Bo0mer/enslaver/model"
)

type FakeEnslaver struct {
	RegisterStub        func(Slave)
	registerMutex       sync.RWMutex
	registerArgsForCall []struct {
		arg1 Slave
	}
	SlavesStub        func() []Slave
	slavesMutex       sync.RWMutex
	slavesArgsForCall []struct{}
	slavesReturns struct {
		result1 []Slave
	}
	ExecuteStub        func(JobRequest) (Job, error)
	executeMutex       sync.RWMutex
	executeArgsForCall []struct {
		arg1 JobRequest
	}
	executeReturns struct {
		result1 Job
		result2 error
	}
}

func (fake *FakeEnslaver) Register(arg1 Slave) {
	fake.registerMutex.Lock()
	fake.registerArgsForCall = append(fake.registerArgsForCall, struct {
		arg1 Slave
	}{arg1})
	fake.registerMutex.Unlock()
	if fake.RegisterStub != nil {
		fake.RegisterStub(arg1)
	}
}

func (fake *FakeEnslaver) RegisterCallCount() int {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	return len(fake.registerArgsForCall)
}

func (fake *FakeEnslaver) RegisterArgsForCall(i int) Slave {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	return fake.registerArgsForCall[i].arg1
}

func (fake *FakeEnslaver) Slaves() []Slave {
	fake.slavesMutex.Lock()
	fake.slavesArgsForCall = append(fake.slavesArgsForCall, struct{}{})
	fake.slavesMutex.Unlock()
	if fake.SlavesStub != nil {
		return fake.SlavesStub()
	} else {
		return fake.slavesReturns.result1
	}
}

func (fake *FakeEnslaver) SlavesCallCount() int {
	fake.slavesMutex.RLock()
	defer fake.slavesMutex.RUnlock()
	return len(fake.slavesArgsForCall)
}

func (fake *FakeEnslaver) SlavesReturns(result1 []Slave) {
	fake.SlavesStub = nil
	fake.slavesReturns = struct {
		result1 []Slave
	}{result1}
}

func (fake *FakeEnslaver) Execute(arg1 JobRequest) (Job, error) {
	fake.executeMutex.Lock()
	fake.executeArgsForCall = append(fake.executeArgsForCall, struct {
		arg1 JobRequest
	}{arg1})
	fake.executeMutex.Unlock()
	if fake.ExecuteStub != nil {
		return fake.ExecuteStub(arg1)
	} else {
		return fake.executeReturns.result1, fake.executeReturns.result2
	}
}

func (fake *FakeEnslaver) ExecuteCallCount() int {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return len(fake.executeArgsForCall)
}

func (fake *FakeEnslaver) ExecuteArgsForCall(i int) JobRequest {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return fake.executeArgsForCall[i].arg1
}

func (fake *FakeEnslaver) ExecuteReturns(result1 Job, result2 error) {
	fake.ExecuteStub = nil
	fake.executeReturns = struct {
		result1 Job
		result2 error
	}{result1, result2}
}

var _ enslaver.Enslaver = new(FakeEnslaver)
